agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent_list'),
    path('create/', AgentCreateView.as_view(), name='agent_create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent_update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent_delete'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from tasks.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace='agents')),
    path('projects/', include('projects.urls', namespace='projects')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password


User = get_user_model()


class AgentModelForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'position',
            'mobile_number',
        )
        labels = {
            'position': 'سمت',
            'mobile_number': 'شماره همراه',
        }

    def save(self, commit=True):
        user = super(AgentModelForm, self).save(commit=False)
        password = self.cleaned_data["password"]
        user.password = make_password(password)
        if commit:
            user.save()
        return user

agents/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Agent
from django.urls import reverse
from .forms import AgentModelForm
from .mixin import OrganisorAndLoginRequiredMixin


class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent_list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.save()
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )

        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_detail.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent_list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"

    def get_success_url(self):
        return reverse("agents:agent_list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

agents/templates/agents/agent_create.html
{% extends "base.html" %} {% load crispy_forms_tags %}


{% block content %}
  <a href="{% url 'agents:agent_list' %}"> بازگشت به فهرست کاربران </a>
  <div class="container">
    <h1>افزودن کاربر جدید</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit">ارسال</button>
  </div>

{% endblock %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %} {% block content %}
<a href="{% url 'agents:agent_list' %}"> بازگشت به کاربران </a>
<div class="container">
  <br />
  <h2>"{{ object }}" را اطمینان دارید که می‌خواهید پاک کنید؟</h2>
  <form method="post">
    {% csrf_token %}
    <br />
    <button type="submit">پاک کردن</button>
    <button type="submit">
      <a href="{% url 'agents:agent_list' %}">لغو</a>
    </button>
  </form>
</div>
{% endblock %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %} {% block content %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="mb-4">
        <h3 class="h3 text-dark">{{ agent.agent_name }}</h3>
      </div>

      <nav class="nav nav-pills flex-column flex-sm-row border-bottom mb-4">
        <a
          class="flex-sm-fill text-sm-center nav-link active"
          href="{% url 'agents:agent_detail' agent.pk %}"
          >مرور کلی</a
        >

        <a
          class="flex-sm-fill text-sm-center nav-link"
          href="{% url 'agents:agent_update' agent.pk %}"
          >به روز رسانی</a
        >
      </nav>

      <div class="list-group">
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">نام کاربری: </span>
          <span class="text-dark">{{ agent.user.usermame }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary"> نام:</span>
          <span class="text-dark">{{ agent.user.first_name }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary"> نام خانوادگی :</span>
          <span class="text-dark">{{ agent.user.last_name }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">سمت :</span>
          <span class="text-dark">{{ agent.user.position }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">تلفن همراه :</span>
          <span class="text-dark">{{ agent.user.mobile_number }}</span>
        </div>
      </div>
      <br />
      <a
        href="{% url 'agents:agent_delete' agent.pk %}"
        class="btn btn-danger"
        onclick="return confirm('می خواهید کاربر را پاک کنید؟');"
      >
        پاک کردن کاربر</a
      >

      <hr />
    </div>
  </div>
</div>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %} {% block content %}

<div class="container mt-5">
  <div class="row justify-content-between mb-3">
    <div class="col">
      <h1>فهرست کاربران</h1>
    </div>
    <div class="col-auto">
      <a href="{% url 'agents:agent_create' %}" class="btn btn-primary"
        >افزودن کاربر جدید</a
      >
    </div>
  </div>

  <hr />

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for agent in object_list %}
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ agent.user.username }}</h5>
          <p class="card-text">{{ agent.user.mobile_number }}</p>
          <a
            href="{% url 'agents:agent_detail' agent.pk %}"
            class="btn btn-secondary"
            >توضیحات بیشتر</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

agents/templates/agents/agent_update.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h3 class="h3 text-dark mb-3">{{ agent.agent_name }}</h3>
      <nav class="nav nav-pills flex-column flex-sm-row mb-4">
        <a
          class="flex-sm-fill text-sm-center nav-link"
          href="{% url 'agents:agent_detail' agent.pk %}"
          >مرور کلی</a
        >

        <a
          class="flex-sm-fill text-sm-center nav-link {% if request.resolver_match.url_name == 'agent_update' %}active{% endif %}"
          href="{% url 'agents:agent_update' agent.pk %}"
          >به‌روزرسانی</a
        >
      </nav>

      <form method="post" enctype="multipart/form-data" class="mb-4">
        {% csrf_token %} {{ form|crispy }}
        <button type="submit" class="btn btn-primary w-100 mt-2">ارسال</button>
      </form>
      {{ form.media }}

      <hr />

      <a
        href="{% url 'agents:agent_delete' agent.pk %}"
        class="btn btn-danger"
        onclick="return confirm('می خواهید کاربر را پاک کنید؟');"
      >
        پاک کردن کاربر</a
      >
    </div>
  </div>
</div>

{% endblock content %}