core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from tasks.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace='agents')),
    path('projects/', include('projects.urls', namespace='projects')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView, TaskDeleteView, TaskDetailView, CategoryDetailView,
    TaskListView, TaskUpdateView, CategoryListView, CategoryUpdateView, TaskCategoryUpdateView,
    CategoryDeleteView, CategoryCreateView, FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView, ProjectSearchView

)


app_name = 'tasks'


urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(),
         name='category-detail'),
    path('categories/<int:pk>/update/',
         CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/',
         CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('<int:pk>/followups/create/',
         FollowUpCreateView.as_view(), name='task-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(),
         name='task-followup-update'),
    path('followups/<int:pk>/delete/',
         FollowUpDeleteView.as_view(), name='task-followup-delete'),
    path('<int:pk>/category/',
         TaskCategoryUpdateView.as_view(), name='task-category-update'),
    path('search/', ProjectSearchView.as_view(), name='project_search'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from projects.models import Project
import jdatetime
from django_jalali.db.models import jDateTimeField


class User(AbstractUser):
    mcom = 'Commercial Manage'
    com = 'expert'
    POSITION_CHOICES = [
        (mcom, 'مدیر بازرگانی'),
        (com, 'کارشناس'),
    ]

    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)
    mobile_number = models.IntegerField(blank=True, null=True)
    position = models.CharField(max_length=100, choices=POSITION_CHOICES)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class TaskManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()


class Task(models.Model):
    task_name = models.CharField(max_length=15)
    info = models.TextField(max_length=150)
    agent = models.ForeignKey(
        'Agent', on_delete=models.SET_NULL, null=True)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    created_at = jDateTimeField(auto_now_add=True)
    date_start = jDateTimeField(null=True, blank=True)
    date_end = jDateTimeField(null=True, blank=True)
    category = models.ForeignKey(
        "Category", related_name="tasks", null=True, blank=True, on_delete=models.SET_NULL)
    converted_date = models.DateTimeField(null=True, blank=True)
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, null=True)
    objects = TaskManager()

    def __str__(self):
        return f"{self.task_name}"

    #  to set the date_start to the date_created value if date_start is not provided.
    def save(self, *args, **kwargs):
        if not self.date_start:
            self.date_start = self.created_at
        super(Task, self).save(*args, **kwargs)


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


def post_user_created_signal(sender, instance, created, **kwargs):
    print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

# Add follow up for Task


def handle_upload_follow_ups(instance, filename):
    return f"task_followups/task_{instance.task.pk}/{filename}"


class FollowUp(models.Model):
    task = models.ForeignKey(
        Task, related_name="followups", on_delete=models.CASCADE)
    date_added = jDateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True, null=True)
    file = models.FileField(null=True, blank=True,
                            upload_to=handle_upload_follow_ups)

    def __str__(self):
        return f"{self.task.task_name} "


class Category(models.Model):
    # New, Contacted, Converted, Unconverted
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from tasks.models import Task, Agent, Category, FollowUp
from projects.models import Project
from django_jalali.forms import jDateTimeField
from django_jalali.admin.widgets import AdminSplitjDateTime


class TaskModelForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = (
            'task_name',
            'info',
            'agent',
            'date_start',
            'date_end',
            'category',
            'project',

        )
        labels = {
            'task_name': 'نام کار',
            'info': 'توضیحات',
            'agent': 'کاربر',
            'date_start': 'تاریخ شروع',
            'date_end': 'تاریخ پایان',
            'category': 'دسته‌بندی',
            'project': 'شماره ثبت سفارش',
        }
        widgets = {
            'date_start': AdminSplitjDateTime(),
            'date_end': AdminSplitjDateTime(),
            # Add other widgets if necessary
        }

    def clean(self):
        pass


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class TaskCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = (
            'category',
        )
        labels = {
            'project': 'Project Name',
            'category': 'وضعیت',
        }


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
        )
        labels = {
            'name': 'نام',
        }


class FollowUpModelForm(forms.ModelForm):
    class Meta:
        model = FollowUp
        fields = (
            'notes',
            'file'
        )
        labels = {
            'notes': 'یادداشت‌ها',
            'file': 'فایل',
        }


# search form
class ProjectSearchForm(forms.Form):
    project_id = forms.IntegerField(label='Project ID')

tasks/views.py
from typing import Any
from django.db import models
from django.shortcuts import render
from tasks.models import Task, Agent, Category, FollowUp
from django.views import generic
from django.db.models.query import QuerySet
from tasks.forms import TaskModelForm, FollowUpModelForm, AssignAgentForm, TaskCategoryUpdateForm, CategoryModelForm, FollowUpModelForm, ProjectSearchForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from agents.mixin import OrganisorAndLoginRequiredMixin
import datetime
from django.utils import timezone
from django.views.generic import FormView
from django.urls import reverse_lazy, reverse


class HomeView(LoginView):
    template_name = "task_home.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        return response

    def form_invalid(self, form):
        messages.error(
            self.request, 'Login failed. Please check your credentials.')
        return super().form_invalid(form)


class TaskListView(LoginRequiredMixin, generic.ListView):
    template_name = 'tasks/task_list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Task.objects.filter(organisation=user.userprofile)
        else:
            queryset = Task.objects.filter(
                organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)

        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'tasks/task_detail.html'
    model = Task
    context_object_name = 'task'

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Task.objects.filter(organisation=user.userprofile)
        else:
            queryset = Task.objects.filter(
                organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'tasks/task_create.html'
    form_class = TaskModelForm
    model = Task

    def get_success_url(self):
        return reverse("tasks:task_list")

    def form_valid(self, form):
        task = form.save(commit=False)
        task.organisation = self.request.user.userprofile
        task.save()
        messages.success(self.request, "You have successfully created a Task")
        return super(TaskCreateView, self).form_valid(form)


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'tasks/task_delete.html'
    queryset = Task.objects.all()
    form_class = TaskModelForm

    def get_success_url(self):
        return reverse('tasks:task_list')


class TaskUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "tasks/task_update.html"
    form_class = TaskModelForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of tasks for the entire organisation
        return Task.objects.filter(organisation=user.userprofile)

    def get_success_url(self):
        return reverse("tasks:task_list")

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this task")
        return super(TaskUpdateView, self).form_valid(form)


class TaskCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "tasks/task_category_update.html"
    form_class = TaskCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of Tasks for the entire organisation
        if user.is_organisor:
            queryset = Task.objects.filter(organisation=user.userprofile)
        else:
            queryset = Task.objects.filter(
                organisation=user.agent.organisation)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_success_url(self):
        return reverse("tasks:task_detail", kwargs={"pk": self.get_object().id})

    def form_valid(self, form):
        task_before_update = self.get_object()
        instance = form.save(commit=False)

        organisation = task_before_update.organisation if hasattr(
            task_before_update, 'organisation') else self.request.user.userprofile

        # Ensure the "Converted" category exists
        converted_category, created = Category.objects.get_or_create(
            name="Converted", defaults={'organisation': organisation})

        if form.cleaned_data["category"] == converted_category:
            # update the date at which this task was converted
            if task_before_update.category != converted_category:
                # this task has now been converted
                instance.converted_date = timezone.now()
        instance.save()
        return super(TaskCategoryUpdateView, self).form_valid(form)


class FollowUpCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "tasks/followup_create.html"
    form_class = FollowUpModelForm

    def get_success_url(self):
        return reverse("tasks:task_detail", kwargs={"pk": self.kwargs["pk"]})

    def get_context_data(self, **kwargs):
        context = super(FollowUpCreateView, self).get_context_data(**kwargs)
        context.update({
            "task": Task.objects.get(pk=self.kwargs["pk"])
        })
        return context

    def form_valid(self, form):
        task = Task.objects.get(pk=self.kwargs["pk"])
        followup = form.save(commit=False)
        followup.task = task
        followup.save()
        return super(FollowUpCreateView, self).form_valid(form)


class FollowUpUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "tasks/followup_update.html"
    form_class = FollowUpModelForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of tasks for the entire organisation
        if user.is_organisor:
            queryset = FollowUp.objects.filter(
                task__organisation=user.userprofile)
        else:
            queryset = FollowUp.objects.filter(
                task__organisation=user.agent.organisation)
            # filter for the agent that is logged in
            queryset = queryset.filter(task__agent__user=user)
        return queryset

    def get_success_url(self):
        return reverse("tasks:task_detail", kwargs={"pk": self.get_object().task.id})


class FollowUpDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "tasks/followup_delete.html"

    def get_success_url(self):
        followup = FollowUp.objects.get(id=self.kwargs["pk"])
        return reverse("tasks:task_detail", kwargs={"pk": followup.task.pk})

    def get_queryset(self):
        user = self.request.user
        # initial queryset of tasks for the entire organisation
        if user.is_organisor:
            queryset = FollowUp.objects.filter(
                task__organisation=user.userprofile)
        else:
            queryset = FollowUp.objects.filter(
                task__organisation=user.agent.organisation)
            # filter for the agent that is logged in
            queryset = queryset.filter(task__agent__user=user)
        return queryset


class AssignAgentView(OrganisorAndLoginRequiredMixin, generic.FormView):
    template_name = "tasks/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("tasks:task-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        task = Task.objects.get(id=self.kwargs["pk"])
        task.agent = agent
        task.save()
        return super(AssignAgentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = "tasks/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        # Get the original queryset of categories
        categories = context['category_list']

        # Update context with categories and their task counts
        categories_with_task_count = []
        for category in categories:
            category.task_count = Task.objects.filter(
                category=category).count()
            categories_with_task_count.append(category)

        context['category_list'] = categories_with_task_count

        if user.is_organisor:
            queryset = Task.objects.filter(organisation=user.userprofile)
        else:
            queryset = Task.objects.filter(
                organisation=user.agent.organisation)

        context['unassigned_task_count'] = queryset.filter(
            category__isnull=True).count()

        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            return Category.objects.filter(organisation=user.userprofile)
        else:
            return Category.objects.filter(organisation=user.agent.organisation)


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "tasks/category_detail.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of tasks for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )

tasks/templates/tasks/assign_agent.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<div class="max-w-lg mx-auto">
  <a class="hover:text-blue-500" href="{% url 'tasks:task-list' %}"
    >Go back to tasks</a
  >
  <div class="py-5 border-t border-gray-200">
    <h1 class="text-4xl text-gray-800">Assign an agent to this task</h1>
  </div>
  <form method="post" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button
      type="submit"
      class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md"
    >
      Submit
    </button>
  </form>
</div>

{% endblock content %}

tasks/templates/tasks/category_delete.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<div class="max-w-lg mx-auto">
  <a class="hover:text-blue-500" href="{% url 'tasks:category-list' %}"
    >Go back to categories</a
  >
  <div class="py-5 border-t border-gray-200">
    <h1 class="text-4xl text-gray-800">
      Are you sure you want to delete {{ object.name }}?
    </h1>
  </div>
  <form method="post" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button
      type="submit"
      class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md"
    >
      Submit
    </button>
  </form>
</div>

{% endblock content %}

tasks/templates/tasks/category_detail.html
{% extends "base.html" %} {% block content %}

<section class="py-5">
  <div class="container">
    <div class="text-center mb-5">
      <h1 class="display-4 text-dark mb-3">
        Tasks in "{{ category.name }}" Category
      </h1>
      <p class="lead">
        Below is a list of tasks categorized under "{{ category.name }}".
      </p>
    </div>

    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">نام</th>
            <th scope="col">توضیحات</th>
            <!-- Other Columns -->
          </tr>
        </thead>
        <tbody>
          {% for task in category.tasks.all %}
          <tr>
            <td>{{ task.task_name }}</td>
            <td>{{ task.info }}</td>
            <!-- Other Task Details -->
          </tr>
          {% empty %}
          <tr>
            <td colspan="2" class="text-center">هیچ کاری الصاق نشده</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

tasks/templates/tasks/category_list.html
{% extends "base.html" %} {% block content %}

<section class="py-5">
  <div class="container">
    <div class="text-center mb-5">
      <h1 class="fw-bold text-dark mb-3">وضعیت ها</h1>
      <a href="{% url 'tasks:category-create' %}" class="btn btn-primary">
        افزودن دسته بندی جدید
      </a>
    </div>

    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead class="table-light">
          <tr>
            <th>نام</th>
            <th>تعداد کاد</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>الصاق نشده</td>
            <td>{{ unassigned_task_count }}</td>
          </tr>
          {% for category in category_list %}
          <tr>
            <td>
              <a
                href="{% url 'tasks:category-detail' category.pk %}"
                class="text-decoration-none"
              >
                {{ category.name }}
              </a>
            </td>
            <td>{{ category.task_count }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

tasks/templates/tasks/category_update.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<div class="max-w-lg mx-auto">
  <a class="hover:text-blue-500" href="{% url 'tasks:category-list' %}"
    >Go back to categories</a
  >
  <div class="py-5 border-t border-gray-200">
    <h1 class="text-4xl text-gray-800">Update {{ object.name }}</h1>
  </div>
  <form method="post" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button
      type="submit"
      class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md"
    >
      Submit
    </button>
  </form>
</div>

{% endblock content %}

tasks/templates/tasks/followup_update.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<div class="max-w-lg mx-auto rounded-md">
  <a
    class="hover:text-blue-500"
    href="{% url 'tasks:task_detail' object.task.pk %}"
    >بازگشت به یادداشتها</a
  >
  <div class="py-5 border-t border-gray-200 rounded-md shadow-sm text-center">
    <h1 class="text-4xl text-gray-800">به‌روزرسانی یادداشت</h1>
  </div>
  <form method="post" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button
      type="submit"
      class="w-full text-blue bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md"
    >
      ارسال
    </button>
  </form>
  <div class="mt-5 pt-5 border-t border-gray-200">
    <a
      href="{% url 'tasks:task-followup-delete' object.pk %}"
      class="text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md"
    >
      پاک کردن
    </a>
  </div>
</div>

{% endblock content %}

tasks/templates/tasks/task_category_update.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h3 class="h3 text-dark mb-3">{{ task.task_name }}</h3>

      <nav class="nav nav-pills flex-column flex-sm-row mb-4">
        <a
          class="flex-sm-fill text-sm-center nav-link {% if request.resolver_match.url_name == 'task_detail' %}active{% endif %}"
          href="{% url 'tasks:task_detail' task.pk %}"
          >نمایش</a
        >
        <a
          class="flex-sm-fill text-sm-center nav-link {% if request.resolver_match.url_name == 'task-category-update' %}active{% endif %}"
          href="{% url 'tasks:task-category-update' task.pk %}"
          >وضعیت</a
        >
        <a
          class="flex-sm-fill text-sm-center nav-link {% if request.resolver_match.url_name == 'task_update' %}active{% endif %}"
          href="{% url 'tasks:task_update' task.pk %}"
          >به‌روزرسانی</a
        >
      </nav>

      <form method="post" class="mb-4">
        {% csrf_token %} {{ form|crispy }}
        <button type="submit" class="btn btn-primary w-100 mt-2">ارسال</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

tasks/templates/tasks/task_detail.html
{% extends "base.html" %} {% block content %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="mb-4">
        <h3 class="h3 text-dark">{{ task.task_name }}</h3>
      </div>

      <nav class="nav nav-pills flex-column flex-sm-row border-bottom mb-4">
        <a
          class="flex-sm-fill text-sm-center nav-link active"
          href="{% url 'tasks:task_detail' task.pk %}"
          >مرور کلی</a
        >
        <a
          class="flex-sm-fill text-sm-center nav-link"
          href="{% url 'tasks:task-category-update' task.pk %}"
          >وضعیت</a
        >
        <a
          class="flex-sm-fill text-sm-center nav-link"
          href="{% url 'tasks:task_update' task.pk %}"
          >به روز رسانی</a
        >
      </nav>

      <div class="list-group">
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">کاربر: </span>
          <span class="text-dark">{{ task.agent }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary"> توضیحات:</span>
          <span class="text-dark">{{ task.info }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary"> وضعیت:</span>
          <span class="text-dark">{{ task.category }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">پروژه‌:</span>
          <span class="text-dark">{{ task.project }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">تاریخ شروع:</span>
          <span class="text-dark">{{ task.date_start }}</span>
        </div>
      </div>

      <a
        href="{% url 'tasks:task-followup-create' task.pk %}"
        class="btn btn-primary my-3"
        >افزودن یادداشت</a
      >
      <a
        href="{% url 'tasks:task_delete' task.pk %}"
        class="btn btn-danger"
        onclick="return confirm('Are you sure you want to delete this task?');"
      >
        پاک کردن کار</a
      >

      <hr />

      {% for followup in task.followups.all %}
      <div class="shadow-sm p-4 mb-4">
        <h5 class="text-secondary">یادداشت</h5>
        <p class="text-dark">{{ followup.notes }}</p>
        <p class="text-muted">{{ followup.date_added }}</p>

        {% if followup.file %}
        <div class="mt-3">
          <h6 class="text-secondary">سندها</h6>
          <a href="{{ followup.file.url }}" download class="text-primary">
            {{ followup.file.name }}
          </a>
        </div>
        {% endif %}

        <form
          action="{% url 'tasks:task-followup-delete' followup.pk %}"
          method="post"
          class="mt-2"
        >
          {% csrf_token %}
          <button
            type="submit"
            class="btn btn-danger"
            onclick="return confirm('Are you sure you want to delete this follow-up?');"
          >
            پاک کردن
          </button>
        </form>
        {{ form.media }}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

tasks/templates/tasks/task_update.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h3 class="h3 text-dark mb-3">{{ task.task_name }}</h3>
      <nav class="nav nav-pills flex-column flex-sm-row mb-4">
        <a
          class="flex-sm-fill text-sm-center nav-link"
          href="{% url 'tasks:task_detail' task.pk %}"
          >مرور کلی</a
        >
        <a
          class="flex-sm-fill text-sm-center nav-link"
          href="{% url 'tasks:task-category-update' task.pk %}"
          >وضعیت</a
        >
        <a
          class="flex-sm-fill text-sm-center nav-link {% if request.resolver_match.url_name == 'task_update' %}active{% endif %}"
          href="{% url 'tasks:task_update' task.pk %}"
          >به‌روزرسانی</a
        >
      </nav>

      <form method="post" enctype="multipart/form-data" class="mb-4">
        {% csrf_token %} {{ form|crispy }}
        <button type="submit" class="btn btn-primary w-100 mt-2">ارسال</button>
      </form>
      {{ form.media }}

      <hr />

      <a
        href="{% url 'tasks:task_delete' task.pk %}"
        class="btn btn-danger"
        onclick="return confirm('Are you sure you want to delete this task?');"
      >
        پاک کردن کار</a
      >
    </div>
  </div>
</div>

{% endblock content %}