core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from tasks.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace='agents')),
    path('projects/', include('projects.urls', namespace='projects')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    ProjectDocumentCreat,
    ProjectDocumentDelete
)

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('create/', ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('<int:pk>/documents/create/',
         ProjectDocumentCreat.as_view(), name='project-document-create'),
    path('documents/<int:pk>/delete/',
         ProjectDocumentDelete.as_view(), name='project-document-delete'),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView, TaskDeleteView, TaskDetailView, CategoryDetailView,
    TaskListView, TaskUpdateView, CategoryListView, CategoryUpdateView, TaskCategoryUpdateView,
    CategoryDeleteView, CategoryCreateView, FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView, ProjectSearchView

)


app_name = 'tasks'


urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(),
         name='category-detail'),
    path('categories/<int:pk>/update/',
         CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/',
         CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('<int:pk>/followups/create/',
         FollowUpCreateView.as_view(), name='task-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(),
         name='task-followup-update'),
    path('followups/<int:pk>/delete/',
         FollowUpDeleteView.as_view(), name='task-followup-delete'),
    path('<int:pk>/category/',
         TaskCategoryUpdateView.as_view(), name='task-category-update'),
    path('search/', ProjectSearchView.as_view(), name='project_search'),
]

projects/models.py
from django.db import models


class Currency(models.Model):
    USD = 'USD'
    EUR = 'EUR'
    AED = 'AED'

    CURRENCY_CHOICES = [
        (USD, 'US Dollars'),
        (EUR, 'Euro'),
        (AED, 'Dirham of Emirates')
    ]

    code = models.CharField(
        max_length=3, choices=CURRENCY_CHOICES, unique=True, primary_key=True)
    name = models.CharField(max_length=50)
    symbol = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f"{self.name} ({self.code})"


class Project(models.Model):
    name = models.CharField(max_length=100)
    proforma_num_reg = models.IntegerField(primary_key=True)
    proforma_name = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    weight = models.PositiveIntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.proforma_num_reg)


class Document(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/', blank=True, null=True)

projects/forms.py
from django import forms
from projects.models import Project, Document


class ProjectModelForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        labels = {
            'name': 'نام کالا',
            'proforma_num_reg': 'شماره ثبت پروفرما',
            'proforma_name': 'شماره پروفرما',
            'price': 'مبلغ',
            'weight': 'وزن',
            'currency': 'واحد ارز'
        }


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = (
            'title',
            'document',
        )
        labels = {
            'title': 'عنوان',
            'document': 'سند'
        }

projects/views.py
from typing import Any
from django.shortcuts import render, redirect, get_object_or_404
from .models import Project, Document
from django.views import generic
from projects.forms import ProjectModelForm, DocumentForm
from agents.mixin import OrganisorAndLoginRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

# CRUD Projects


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    context_object_name = 'projects'
    template_name = 'projects/project_list.html'


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    context_object_name = 'project'
    template_name = 'projects/project_detail.html'


class ProjectCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    form_class = ProjectModelForm
    template_name = 'projects/project_create.html'

    def get_success_url(self):
        return reverse('projects:project_list')


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectModelForm
    template_name = 'projects/project_update.html'

    def get_success_url(self):
        return reverse('project_detail', kwargs={'pk': self.object.pk})


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    context_object_name = 'project'
    template_name = 'projects/project_delete.html'

    def get_success_url(self):
        return reverse('projects:project_list')


class ProjectDocumentCreat(LoginRequiredMixin, generic.CreateView):
    form_class = DocumentForm
    template_name = 'projects/document_create.html'

    def get_success_url(self):
        return reverse('projects:project_detail', kwargs={"pk": self.kwargs["pk"]})

    def get_context_data(self, **kwargs):
        context = super(ProjectDocumentCreat, self).get_context_data(**kwargs)
        context.update({
            "project": Project.objects.get(pk=self.kwargs["pk"])
        })
        return context

    def form_valid(self, form):
        project = Project.objects.get(pk=self.kwargs["pk"])
        document = form.save(commit=False)
        document.project = project
        document.save()
        return super().form_valid(form)


class ProjectDocumentDelete(LoginRequiredMixin, generic.DeleteView):
    template_name = 'projects/document_delete.html'

    def get_object(self, queryset=None):
        """ Hook to ensure object is fetched from your custom queryset. """
        # You can also add additional filters here if needed
        return get_object_or_404(Document, pk=self.kwargs['pk'])

    def get_success_url(self):
        document = Document.objects.get(id=self.kwargs["pk"])
        return reverse("projects:project_detail", kwargs={"pk": document.project.pk})

projects/templates/projects/document_create.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<div class="max-w-lg mx-auto">
  <a
    class="hover:text-blue-500"
    href="{% url 'projects:project_detail' project.pk %}"
    >بازگشت به {{ project }}</a
  >
  <div class="py-5 border-t border-gray-200">
    <h1 class="text-4xl text-gray-800">اضافه کردن سند</h1>
  </div>
  <form method="post" class="mt-5" enctype="multipart/form-data">
    {% csrf_token %} {{ form|crispy }}
    <button
      type="submit"
      class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md"
    >
      ارسال
    </button>
  </form>
</div>

{% endblock content %}

projects/templates/projects/document_delete.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<div class="max-w-lg mx-auto">
  <a
    class="hover:text-blue-500"
    href="{% url 'tasks:task_detail' object.task.pk %}"
    >Go back to task</a
  >
  <div class="py-5 border-t border-gray-200">
    <h1 class="text-4xl text-gray-800">
      Are you sure you want to delete this followup?
    </h1>
  </div>
  <form method="post" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button
      type="submit"
      class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md"
    >
      ارسال
    </button>
  </form>
</div>

{% endblock content %}

projects/templates/projects/project_create.html
{% extends "base.html" %} 


{% block content %}{% load crispy_forms_tags %}
  <a href="/projects/"> بازگشت به فهرست </a>
  <div class="container">
    <h1>افزودن پروژه‌ جدید</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit">ارسال</button>
  </div>

{% endblock %}

projects/templates/projects/project_delete.html
{% extends "base.html" %} {% block content %}
<a href="{% url 'projects:project_list' %}"> بازگشت به فهرست </a>
<div class="container">
  <h2>اطمینان دارید که می‌خواهید پاک کنید؟ "{{ object }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">پاک کردن</button>
    <a href="{% url 'projects:project_list' %}">لغو</a>
  </form>
</div>
{% endblock content %}

projects/templates/projects/project_detail.html
{% extends "base.html" %} {% block content %}

<div class="container py-5" dir="rtl">
  <div class="row justify-content-center">
    <!-- Main Content Column -->
    <div class="col-lg-8 shadow-sm">
      <h3 class="h3 text-dark mb-4">{{ project.name }}</h3>

      <!-- Navigation Tabs -->
      <nav class="nav nav-pills flex-column flex-sm-row mb-4">
        <a
          class="flex-sm-fill text-sm-center nav-link active"
          href="{% url 'projects:project_detail' project.pk %}"
          >جزییات</a
        >
        <a
          class="flex-sm-fill text-sm-center nav-link"
          href="{% url 'projects:project_update' project.pk %}"
          >به‌روزرسانی
        </a>
      </nav>

      <!-- Project Details -->
      <div class="list-group d-flex">
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">نام کالا:</span>
          <span class="text-dark">{{ project.name }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">شماره ثبت سفارش :</span>
          <span class="text-dark">{{ project.proforma_num_reg}}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">شماره پروفرما : </span>
          <span class="text-dark">{{ project.proforma_name }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">مبلغ : </span>
          <span class="text-dark">{{ project.price }}</span>
          <span class="text-dark">{{ project.currency }}</span>
        </div>
        <div class="list-group-item d-flex justify-content-between">
          <span class="text-secondary">وزن : </span>
          <span class="text-dark">{{ project.weight }}</span>
          <span class="text-dark">کیلوگرم</span>
        </div>
      </div>
    </div>

    <!-- Right Sidebar Column for Document and Document History -->
    <div class="col-lg-4">
      <!-- Document Section -->
      <div class="mb-4 p-3 shadow-sm">
        <h4>اسناد</h4>
        <div>
          {% for document in project.document_set.all %}
          <div class="shadow-sm p-4 mb-4">
            <h6 class="text-secondary">{{ document.title }}</h6>
            <a
              href="{{ document.document.url }}"
              class="btn btn-outline-secondary btn-sm mb-2"
              >نمایش</a
            >
            <form
              action="{% url 'projects:project-document-delete' document.pk %}"
              method="post"
              class="d-inline"
            >
              {% csrf_token %}
              <button
                type="submit"
                class="btn btn-danger btn-sm"
                onclick="return confirm('Are you sure you want to delete this Document?');"
              >
                پاک کردن
              </button>
            </form>
          </div>
          {% endfor %}
          <a
            href="{% url 'projects:project-document-create' project.pk %}"
            class="btn btn-primary"
            >افزودن سند</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

projects/templates/projects/project_list.html
{% extends "base.html" %} {% block content %}

<div class="container mt-5">
  <div class="row justify-content-between mb-3">
    <div class="col">
      <h1>فهرست پروژه‌</h1>
    </div>
    {% if request.user.is_organisor %}
    <div class="col-auto">
      <a href="{% url 'projects:project_create' %}" class="btn btn-primary">
        افزودن پروژه‌ جدید
      </a>
    </div>
    {% endif %}
  </div>

  <hr />

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for project in projects %}
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ project.name }}</h5>
          <p class="card-text">{{ project.address }}</p>
          <a
            href="{% url 'projects:project_detail' project.pk %}"
            class="btn btn-secondary"
          >
            توضیحات بیشتر
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

projects/templates/projects/project_update.html
{% extends "base.html" %} {% block content %}

<div class="container py-5">
  <div class="row justify-content-center">
    <!-- Main Content Column -->
    <div class="col-lg-8 shadow-sm">
      <h3 class="h3 text-dark mb-4">{{ project.name }}</h3>

      <!-- Navigation Tabs -->
      <nav class="nav nav-pills flex-column flex-sm-row mb-4">
        <a
          class="flex-sm-fill text-sm-center nav-link"
          href="{% url 'projects:project_detail' project.pk %}"
          >مرور کلی</a
        >
        <a
          class="flex-sm-fill text-sm-center nav-link active"
          href="{% url 'projects:project_update' project.pk %}"
          >به روزرسانی</a
        >
      </nav>

      <!-- Project Update Form -->
      <form method="post" class="mb-4">
        {% csrf_token %} {{ form.as_p }}
        <div class="d-flex justify-content-between align-items-center">
          <button type="submit" class="btn btn-primary">به روزرسانی</button>
          <a
            href="{% url 'projects:project_delete' project.pk %}"
            class="btn btn-danger"
            onclick="return confirm('Are you sure you want to delete this project?');"
            >پاک کردن پروژه‌</a
          >
        </div>
      </form>
    </div>

    <!-- Right Sidebar Column for Document and Document History -->
    <div class="col-lg-4">
      <!-- Document Section -->
      <div class="mb-4 p-3 shadow-sm">
        <h4>اسناد</h4>
        {% for document in project.document_set.all %}
        <div class="shadow-sm p-4 mb-4">
          <h6 class="text-secondary">{{ document.title }}</h6>
          <a
            href="{{ document.document.url }}"
            class="btn btn-outline-secondary btn-sm mb-2"
            >نمایش</a
          >
          <form
            action="{% url 'projects:project-document-delete' document.pk %}"
            method="post"
            class="d-inline"
          >
            {% csrf_token %}
            <button
              type="submit"
              class="btn btn-danger btn-sm"
              onclick="return confirm('Are you sure you want to delete this Document?');"
            >
              پاک کردن
            </button>
          </form>
        </div>
        {% endfor %}
        <a
          href="{% url 'projects:project-document-create' project.pk %}"
          class="btn btn-primary"
          >افزودن سند</a
        >
      </div>
    </div>
  </div>
</div>

{% endblock %}