agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent_list'),
    path('create/', AgentCreateView.as_view(), name='agent_create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent_update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent_delete'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from tasks.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace='agents')),
    path('projects/', include('projects.urls', namespace='projects')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    ProjectDocumentCreat,
    ProjectDocumentDelete
)

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('create/', ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('<int:pk>/documents/create/',
         ProjectDocumentCreat.as_view(), name='project-document-create'),
    path('documents/<int:pk>/delete/',
         ProjectDocumentDelete.as_view(), name='project-document-delete'),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView, TaskDeleteView, TaskDetailView, CategoryDetailView,
    TaskListView, TaskUpdateView, CategoryListView, CategoryUpdateView, TaskCategoryUpdateView,
    CategoryDeleteView, CategoryCreateView, FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView, ProjectSearchView

)


app_name = 'tasks'


urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(),
         name='category-detail'),
    path('categories/<int:pk>/update/',
         CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/',
         CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('<int:pk>/followups/create/',
         FollowUpCreateView.as_view(), name='task-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(),
         name='task-followup-update'),
    path('followups/<int:pk>/delete/',
         FollowUpDeleteView.as_view(), name='task-followup-delete'),
    path('<int:pk>/category/',
         TaskCategoryUpdateView.as_view(), name='task-category-update'),
    path('search/', ProjectSearchView.as_view(), name='project_search'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Gunash Project Management</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href=" {% static 'admin/css/widgets.css' %}" />
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container" dir="rtl">{% block content %} {% endblock %}</div>

    <script href="{% static 'admin/js/core.js' %}"></script>
    <script
      href="{% static 'admin/jquery.ui.datepicker.jalali/scripts/jquery-1.10.2.min.js' %}"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <script src="/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js"></script>
    <script src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
    <script src="/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js"></script>
    <script src="/static/admin/jquery.ui.datepicker.jalali/scripts/calendar.js"></script>
    <script src="/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js"></script>
  </body>
</html>

templates/footer.html
<footer class="bg-dark text-white mt-4">
  <div class="container-fluid py-3">
    <div class="row">
      <div class="col-md-6 text-center text-md-left">
        <p class="mb-0">&copy; 2023 Gnash Chemical</p>
      </div>
      <div class="col-md-6 text-center text-md-right">
        <p class="mb-0">
          Designed by <a href="#" class="text-white">Iman Narestan</a>
        </p>
      </div>
    </div>
  </div>
</footer>

templates/navbar.html
<nav
  class="navbar navbar-expand-lg navbar-light"
  style="background-color: #e3f2fd"
  dir="rtl"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'tasks:task_list' %}">
      Gunash Task Manager
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ request.user.username }}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'logout' %}">خروج</a></li>
            <!-- Additional user options can go here -->
          </ul>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:task_list' %}">کارها</a>
        </li>
        {% if request.user.is_organisor %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'agents:agent_list' %}">کاربران</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'projects:project_list' %}"
            >پروژه‌ها</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:category-list' %}"
            >دسته‌بندی‌ها</a
          >
        </li>
        {% endif %} {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/task_home.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="text-gray-700 body-font">
  <div
    class="container mx-auto flex px-5 py-24 items-center justify-center flex-col"
  >
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        Gunash Taskmanager
      </h1>
      <p class="mb-8 leading-relaxed">Taskmanager</p>
      <div class="flex justify-center">
        <a
          href="{% url 'login' %}"
          class="inline-flex text-blue bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        >
          Login to get started
        </a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}